name: Kernel Extractor

on:
  workflow_dispatch:
    inputs:
      BOOT_URL:
        description: 'URL of the Boot Image'
        required: true
        default: 'https://github.com/YOUR_USERNAME/REPOSITORY/releases/...'
      DEVICE_NAME:
        description: 'Name of the Device'
        required: true
        default: 'Z Fold 3 5G'

permissions:
  contents: write

env:
  TZ: America/Santiago

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Prepare the environment
      run: |
        sudo apt install git wget lz4 tar openssl python3 -y

    - name: Fetch image from URL
      run: |
        ls
        pwd
        wget ${{ github.event.inputs.BOOT_URL }}
        wget https://github.com/bm0x/Samsung-Public-Releases/releases/download/vbmeta_gsi/vbmeta-gsi.tar

    - name: Montage and Extract of the Kernel Image
      run: |
        chmod a+x extractor.sh
        chmod a+x magiskboot
        ./extractor.sh || true
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          /home/runner/work/kernel-extractor-gh-actions/kernel-extractor-gh-actions/output/*
        name: Extracted Kernel for ${{ github.event.inputs.DEVICE_NAME }}
        tag_name: ${{ github.run_id }}
        body: Kernel extracted from ${{ github.event.inputs.BOOT_URL }} for ${{ github.event.inputs.DEVICE_NAME }} by ${{ github.actor }} at ${{ github.run_number }}. Added Magisk and AVB 2.0 support and VBMeta for GSI flashing for Treble devices.
      env:
        GITHUB_TOKEN: ${{ github.token }}